import {
  FamilyMember,
  Income,
  Loan,
  Debt,
  ExpenseCategory,
  Expense,
  UtilityBill,
  SavingsGoal,
  Investment,
  UserSettings,
} from '../types';
import { generateAmortizationSchedule } from '../utils/finance';

export const initialMembers: FamilyMember[] = [
  { id: 'mem-1', name: 'Anvar', role: 'ota', avatarColor: '#059669' },
  { id: 'mem-2', name: 'Nodira', role: 'ona', avatarColor: '#0284c7' },
  { id: 'mem-3', name: 'Jasur', role: 'farzand', avatarColor: '#d97706' },
  { id: 'mem-4', name: 'Madina', role: 'farzand', avatarColor: '#db2777' },
];

export const initialIncomes: Income[] = [
  {
    id: 'inc-1',
    title: 'Anvar — Asosiy maosh (IT muhandis)',
    memberId: 'mem-1',
    amount: 14000000,
    dayOfMonth: 5,
    isRecurring: true,
    category: 'maosh',
    dateCreated: '2026-01-10',
  },
  {
    id: 'inc-2',
    title: 'Nodira — Maktab maoshi va repetitorlik',
    memberId: 'mem-2',
    amount: 6500000,
    dayOfMonth: 10,
    isRecurring: true,
    category: 'maosh',
    dateCreated: '2026-01-10',
  },
  {
    id: 'inc-3',
    title: 'Xonadon ijarasidan daromad',
    memberId: 'mem-1',
    amount: 3500000,
    dayOfMonth: 1,
    isRecurring: true,
    category: 'ijara',
    dateCreated: '2026-02-01',
  },
];

export const initialLoans: Loan[] = [
  {
    id: 'loan-1',
    name: 'Ipoteka xonadon',
    bankName: 'Ipoteka Bank',
    type: 'ipoteka',
    originalPrincipal: 350000000,
    remainingPrincipal: 310000000,
    annualInterestRate: 17,
    paymentType: 'annuity',
    startDate: '2024-05-10',
    termMonths: 120,
    monthlyPayment: 5400000,
    paymentDueDay: 10,
    prepaymentPenaltyRate: 0,
    isPaidOff: false,
    notes: 'Birlamchi bozor subsidiyali ipoteka',
    schedule: generateAmortizationSchedule(310000000, 17, 100, 'annuity'),
  },
  {
    id: 'loan-2',
    name: 'Avtokredit Chevrolet Tracker',
    bankName: 'Hamkorbank',
    type: 'avtokredit',
    originalPrincipal: 180000000,
    remainingPrincipal: 95000000,
    annualInterestRate: 23,
    paymentType: 'annuity',
    startDate: '2025-02-15',
    termMonths: 48,
    monthlyPayment: 4800000,
    paymentDueDay: 15,
    prepaymentPenaltyRate: 0,
    isPaidOff: false,
    notes: 'Avtosalon rasmiylashtiruvi',
    schedule: generateAmortizationSchedule(95000000, 23, 26, 'annuity'),
  },
  {
    id: 'loan-3',
    name: 'Mikroqarz ta\'mir uchun',
    bankName: 'Anorbank',
    type: 'mikroqarz',
    originalPrincipal: 25000000,
    remainingPrincipal: 12000000,
    annualInterestRate: 32,
    paymentType: 'annuity',
    startDate: '2025-09-20',
    termMonths: 24,
    monthlyPayment: 1450000,
    paymentDueDay: 20,
    prepaymentPenaltyRate: 0,
    isPaidOff: false,
    notes: 'Yuqori foizli qisqa muddatli kredit',
    schedule: generateAmortizationSchedule(12000000, 32, 11, 'annuity'),
  },
  {
    id: 'loan-4',
    name: 'Telefon nasiyasi (iPhone 15)',
    bankName: 'Uzum Nasiya',
    type: 'nasiya',
    originalPrincipal: 12000000,
    remainingPrincipal: 4000000,
    annualInterestRate: 28,
    paymentType: 'annuity',
    startDate: '2025-11-25',
    termMonths: 12,
    monthlyPayment: 1150000,
    paymentDueDay: 25,
    prepaymentPenaltyRate: 0,
    isPaidOff: false,
    notes: '12 oylik muddatli to\'lov',
    schedule: generateAmortizationSchedule(4000000, 28, 4, 'annuity'),
  },
];

export const initialDebts: Debt[] = [
  {
    id: 'debt-1',
    type: 'borrowed',
    counterparty: 'Rustam aka (tog\'a)',
    originalAmount: 15000000,
    remainingAmount: 10000000,
    dueDate: '2026-12-30',
    isInterestFree: true,
    notes: 'To\'y xarajatlariga olingan, foizsiz',
    isResolved: false,
    dateCreated: '2025-10-01',
  },
  {
    id: 'debt-2',
    type: 'lent',
    counterparty: 'Shavkat do\'stim',
    originalAmount: 5000000,
    remainingAmount: 3000000,
    dueDate: '2026-10-15',
    isInterestFree: true,
    notes: 'Biznes aylanmasi uchun berilgan',
    isResolved: false,
    dateCreated: '2026-06-15',
  },
];

export const initialCategories: ExpenseCategory[] = [
  {
    id: 'cat-1',
    name: 'Oziq-ovqat va bozor',
    iconName: 'ShoppingBag',
    budgetLimit: 5000000,
    color: '#10b981',
    isEssential: true,
  },
  {
    id: 'cat-2',
    name: 'Kommunal va uy-joy',
    iconName: 'Home',
    budgetLimit: 1200000,
    color: '#06b6d4',
    isEssential: true,
  },
  {
    id: 'cat-3',
    name: 'Transport va yoqilg\'i',
    iconName: 'Car',
    budgetLimit: 1800000,
    color: '#3b82f6',
    isEssential: true,
  },
  {
    id: 'cat-4',
    name: 'Bolalar va ta\'lim',
    iconName: 'GraduationCap',
    budgetLimit: 2500000,
    color: '#8b5cf6',
    isEssential: true,
  },
  {
    id: 'cat-5',
    name: 'Salomatlik va dori-darmon',
    iconName: 'HeartPulse',
    budgetLimit: 800000,
    color: '#ec4899',
    isEssential: true,
  },
  {
    id: 'cat-6',
    name: 'Kiyim-kechak',
    iconName: 'Shirt',
    budgetLimit: 1500000,
    color: '#f59e0b',
    isEssential: false,
  },
  {
    id: 'cat-7',
    name: 'Kafe va restoranlar',
    iconName: 'Utensils',
    budgetLimit: 1200000,
    color: '#f97316',
    isEssential: false,
  },
  {
    id: 'cat-8',
    name: 'To\'y, ehson va marosimlar',
    iconName: 'Gift',
    budgetLimit: 2000000,
    color: '#e11d48',
    isEssential: false,
  },
  {
    id: 'cat-9',
    name: 'Aloqa va internet',
    iconName: 'Wifi',
    budgetLimit: 400000,
    color: '#14b8a6',
    isEssential: true,
  },
  {
    id: 'cat-10',
    name: 'Boshqa xarajatlar',
    iconName: 'MoreHorizontal',
    budgetLimit: 1000000,
    color: '#64748b',
    isEssential: false,
  },
];

export const initialExpenses: Expense[] = [
  {
    id: 'exp-1',
    title: 'Qo\'yliq bozori haftalik xarid',
    amount: 1250000,
    categoryId: 'cat-1',
    memberId: 'mem-1',
    date: '2026-09-21',
    isRecurring: false,
    notes: 'Go\'sht, sabzavot va mevalar',
  },
  {
    id: 'exp-2',
    title: 'Benzin (AI-95 60 litr)',
    amount: 680000,
    categoryId: 'cat-3',
    memberId: 'mem-1',
    date: '2026-09-20',
    isRecurring: false,
    notes: 'Oylik yoqilg\'i to\'ldirish',
  },
  {
    id: 'exp-3',
    title: 'Jasurning ingliz tili kursi',
    amount: 750000,
    categoryId: 'cat-4',
    memberId: 'mem-2',
    date: '2026-09-15',
    isRecurring: true,
    notes: 'Cambridge o\'quv markazi',
  },
  {
    id: 'exp-4',
    title: 'Korzinka supermarketi xaridlar',
    amount: 840000,
    categoryId: 'cat-1',
    memberId: 'mem-2',
    date: '2026-09-18',
    isRecurring: false,
  },
  {
    id: 'exp-5',
    title: 'Qarindosh to\'yiga sovg\'a',
    amount: 1500000,
    categoryId: 'cat-8',
    memberId: 'mem-1',
    date: '2026-09-12',
    isRecurring: false,
    notes: 'Tog\'amizning qizlarining nikoh to\'yi',
  },
  {
    id: 'exp-6',
    title: 'Dorixona (vitaminlar va dori)',
    amount: 320000,
    categoryId: 'cat-5',
    memberId: 'mem-2',
    date: '2026-09-19',
    isRecurring: false,
  },
  {
    id: 'exp-7',
    title: 'Oilaviy tushlik (Milliy taomlar)',
    amount: 450000,
    categoryId: 'cat-7',
    memberId: 'mem-1',
    date: '2026-09-14',
    isRecurring: false,
  },
  {
    id: 'exp-8',
    title: 'Sarkor Telecom optik internet',
    amount: 180000,
    categoryId: 'cat-9',
    memberId: 'mem-1',
    date: '2026-09-05',
    isRecurring: true,
  },
  // O'tgan oy (Avgust 2026) xarajatlar tarixi
  {
    id: 'exp-aug-1',
    title: 'Maktab formasi va darsliklar (Farzandlar)',
    amount: 1850000,
    categoryId: 'cat-4',
    memberId: 'mem-2',
    date: '2026-08-25',
    isRecurring: false,
    notes: 'Yangi o\'quv yiliga tayyorgarlik',
  },
  {
    id: 'exp-aug-2',
    title: 'Bozorlik (Go\'sht va oziq-ovqat zaxirasi)',
    amount: 2100000,
    categoryId: 'cat-1',
    memberId: 'mem-1',
    date: '2026-08-18',
    isRecurring: false,
  },
  {
    id: 'exp-aug-3',
    title: 'Avtomobil ehtiyot qismlari va servis',
    amount: 950000,
    categoryId: 'cat-3',
    memberId: 'mem-1',
    date: '2026-08-12',
    isRecurring: false,
  },
  {
    id: 'exp-aug-4',
    title: 'To\'y va marosim xarajatlari',
    amount: 1200000,
    categoryId: 'cat-8',
    memberId: 'mem-1',
    date: '2026-08-08',
    isRecurring: false,
  },
  {
    id: 'exp-aug-5',
    title: 'Yozgi kiyim-kechak xaridi',
    amount: 850000,
    categoryId: 'cat-6',
    memberId: 'mem-2',
    date: '2026-08-04',
    isRecurring: false,
  },
  // 2 oy oldin (Iyul 2026) xarajatlar tarixi
  {
    id: 'exp-jul-1',
    title: 'Oziq-ovqat va ro\'zg\'or xarajatlari',
    amount: 1950000,
    categoryId: 'cat-1',
    memberId: 'mem-1',
    date: '2026-07-22',
    isRecurring: false,
  },
  {
    id: 'exp-jul-2',
    title: 'Oilaviy dam olish va bolalar attraksionlari',
    amount: 980000,
    categoryId: 'cat-7',
    memberId: 'mem-1',
    date: '2026-07-16',
    isRecurring: false,
  },
  {
    id: 'exp-jul-3',
    title: 'Benzin va transport yoqilg\'isi',
    amount: 720000,
    categoryId: 'cat-3',
    memberId: 'mem-1',
    date: '2026-07-10',
    isRecurring: false,
  },
  {
    id: 'exp-jul-4',
    title: 'Stomatolog va tibbiy ko\'rik',
    amount: 650000,
    categoryId: 'cat-5',
    memberId: 'mem-2',
    date: '2026-07-05',
    isRecurring: false,
  },
];

export const initialUtilities: UtilityBill[] = [
  {
    id: 'util-1',
    type: 'electricity',
    name: 'Elektr energiyasi (Toshkent ShTH)',
    accountNumber: '10485923',
    amount: 320000,
    meterReadingCurrent: 4850,
    meterReadingPrevious: 4490,
    isPaid: false,
    dueDate: '2026-09-28',
    monthYear: '2026-09',
  },
  {
    id: 'util-2',
    type: 'gas',
    name: 'Tabiiy gaz (Hududgaz)',
    accountNumber: '4491028',
    amount: 145000,
    meterReadingCurrent: 2890,
    meterReadingPrevious: 2780,
    isPaid: false,
    dueDate: '2026-09-29',
    monthYear: '2026-09',
  },
  {
    id: 'util-3',
    type: 'cold_water',
    name: 'Sovuq suv va kanalizatsiya',
    accountNumber: '992014',
    amount: 85000,
    meterReadingCurrent: 642,
    meterReadingPrevious: 618,
    isPaid: true,
    dueDate: '2026-09-25',
    lastPaidDate: '2026-09-22',
    monthYear: '2026-09',
  },
  {
    id: 'util-4',
    type: 'trash',
    name: 'Chiqindi (Maxsustrans)',
    amount: 44000,
    isPaid: true,
    dueDate: '2026-09-20',
    lastPaidDate: '2026-09-18',
    monthYear: '2026-09',
  },
  {
    id: 'util-5',
    type: 'housing',
    name: 'Uy-joy mulkdorlari shirkati (kvartplata)',
    amount: 120000,
    isPaid: false,
    dueDate: '2026-09-30',
    monthYear: '2026-09',
  },
  {
    id: 'util-6',
    type: 'internet',
    name: 'Uy interneti (GPON)',
    amount: 180000,
    isPaid: true,
    dueDate: '2026-09-05',
    lastPaidDate: '2026-09-04',
    monthYear: '2026-09',
  },
];

export const initialSavingsGoals: SavingsGoal[] = [
  {
    id: 'goal-1',
    name: 'Favqulodda avariya zaxirasi (3 oylik)',
    targetAmount: 30000000,
    currentAmount: 14000000,
    targetDate: '2027-01-01',
    category: 'Zaxira',
    monthlyContributionNeeded: 4000000,
    isAchieved: false,
  },
  {
    id: 'goal-2',
    name: 'Ota-onamiz uchun Haj/Umra safari',
    targetAmount: 60000000,
    currentAmount: 28000000,
    targetDate: '2027-06-01',
    category: 'Ziyorat',
    monthlyContributionNeeded: 3500000,
    isAchieved: false,
  },
  {
    id: 'goal-3',
    name: 'Farzandlar oliygoh ta\'lim fondi',
    targetAmount: 80000000,
    currentAmount: 18000000,
    targetDate: '2029-09-01',
    category: 'Ta\'lim',
    monthlyContributionNeeded: 1800000,
    isAchieved: false,
  },
];

export const initialInvestments: Investment[] = [
  {
    id: 'inv-1',
    name: 'Ipak Yo\'li Bank — Milliy depozit (21% yillik)',
    type: 'deposit',
    investedAmount: 15000000,
    currentValue: 16800000,
    expectedAnnualReturnRate: 21,
    startDate: '2026-01-15',
    notes: 'Kafolatlangan oylik foiz to\'lovi',
  },
  {
    id: 'inv-2',
    name: 'Markaziy Bank oltin quymasi (10 gramm 999.9)',
    type: 'gold',
    investedAmount: 11200000,
    currentValue: 12900000,
    expectedAnnualReturnRate: 15,
    startDate: '2025-08-10',
    notes: 'Inflyatsiyadan himoyalanish uchun',
  },
  {
    id: 'inv-3',
    name: 'AQSH Dollari naqd jamg\'armasi ($1 200)',
    type: 'currency',
    investedAmount: 14800000,
    currentValue: 15420000,
    expectedAnnualReturnRate: 8,
    startDate: '2025-10-01',
  },
];

export const initialSettings: UserSettings = {
  currency: 'UZS',
  usdExchangeRate: 12850,
  language: 'uz',
  theme: 'light',
  monthStartDay: 1,
  pinCode: null,
  isLocked: false,
  onboardingCompleted: true,
  hasCompletedOnboarding: true,
};
